### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/DKTwitterReverseAuth#1]
- [x]  demo.gif
- [x]  update readme
- [x]  0.1 tag on repo 
- [x]  push pod spec 
- [x] clean history commits
- [x] rewrite TWTSignedRequest
- [x] rewrite Api manager?
- [x] api manager property 
- [x] rename to jsonResponse
- [x] integrate dk signed request and dk api manager
